### PR TITLE
Maybe mitigate the bad-tiles issue

### PR DESCRIPTION
**Pull request by pkgw**
I realized that while I had fixed the SDK to hopefully mitigate the issue with certain tiles not loading, your HTML files were referencing the new-but-not-new-enough pywwt version of the SDK. Changing to the centralized version changes the behavior in a way that I hope will help.

### CODE REVIEW

**Comment by pkgw** [comment]
@patudom It's going to be hard to test, but this change should help mitigate the failed-tile issues ... I think we'll just have to deploy it and keep an eye on things, though.

**Comment by patudom** [comment]
Got it - thanks, @pkgw. So we should point all the other interactives to this same new .js file?

**Comment by pkgw** [comment]
@patudom It's not exactly urgent to do so, but yes, you should.

**Comment by patudom** [comment]
All set - [star life cycle](https://github.com/wwt-ambassadors/star-life-cycle/pull/33) and [solar system explorer](https://github.com/wwt-ambassadors/solar-system-explorer/pull/61).

**Pull request merged**
